// <auto-generated />
using System;
using CloudApiReliabilityDashboard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudApiReliabilityDashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002224558_AddEndpointChecks")]
    partial class AddEndpointChecks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudApiReliabilityDashboard.Api.Data.CheckResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndpointId")
                        .HasColumnType("int");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.ToTable("CheckResults");
                });

            modelBuilder.Entity("CloudApiReliabilityDashboard.Api.Data.Endpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("CloudApiReliabilityDashboard.Api.Data.CheckResult", b =>
                {
                    b.HasOne("CloudApiReliabilityDashboard.Api.Data.Endpoint", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
